### ISSUE TITLE
Model weights cannot be downloaded

### ISSUE THREAD

**Issue by BananaTonic** [allenai/figureseer#3]
Hello,
I have been trying to run `aws s3 cp --recursive s3://ai2-website/data/figureseer/neural-networks/ data/models/neural-networks/`. However, I keep getting this error.

**fatal error: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied**

Although `aws configure` was set as below, this error does not solve.

- AWS AccessKey ID [None]: which was created when IAM user generating.
- AWS Secret Access Key [None]: which was created when IAM user generating.
- Default region name [None]: us-east-1
- Default output format [None]: json

Can I tell me how to go around this issue?

**Comment by fpsluozi** [comment]
Same issue here. Have you got the weight files yet @BananaTonic ?

**Comment by schmmd** [comment]
Fixed by https://github.com/allenai/figureseer/pull/4
